package pt.ligix.app.ui.common

data class AppStrings(
    val languageCode: String,
    val languageName: String,
    val portuguese: String,
    val english: String,
    val notifications: String,
    val noNotifications: String,
    val clear: String,
    val home: String,
    val search: String,
    val internship: String,
    val internships: String,
    val students: String,
    val candidates: String,
    val mentors: String,
    val chat: String,
    val profile: String,
    val userInfoTitle: String,
    val userNameLabel: String,
    val edit: String,
    val cancel: String,
    val save: String,
    val information: String,
    val personalInfo: String,
    val contactInfo: String,
    val academicData: String,
    val professionalData: String,
    val institutionalInfo: String,
    val companyData: String,
    val settings: String,
    val language: String,
    val logout: String,
    val fullName: String,
    val corporateEmail: String,
    val institutionalEmail: String,
    val email: String,
    val mobile: String,
    val phone: String,
    val workArea: String,
    val educationInstitution: String,
    val course: String,
    val studentNumber: String,
    val address: String,
    val description: String,
    val teacherRole: String,
    val companySupervisorRole: String,
    val companyRole: String,
    val studentRole: String,
    val certifiedCompany: String,
    val pendingApproval: String,
    val messages: String,
    val close: String,
    val selectInstitution: String,
    val searchByNameOrAcronym: String,
    val noInstitutionsFound: String,
    val hello: String,
    val dashboardWelcome: String,
    val activeMentees: String,
    val activitiesThisWeek: String,
    val missingEvaluations: String,
    val recentActivity: String,
    val noRecentActivity: String,
    val registeredActivity: String,
    val viewActivities: String,
    val myMentees: String,
    val menteesSubtitle: String,
    val filterByNameOrCourse: String,
    val noMentees: String,
    val hostCompany: String,
    val undefinedCompany: String,
    val undefinedCourse: String,
    val viewDetailsDiary: String,
    val studentJourneySummary: String,
    val myStatus: String,
    val activeApplicationsTracking: String,
    val noApplications: String,
    val searchAndApplyInternships: String,
    val searchInternships: String,
    val registerActivity: String,
    val hourProgress: String,
    val accumulatedHoursSemester: String,
    val cancelApplication: String,
    val removeApplication: String,
    val cancelApplicationQuestion: String,
    val removeApplicationQuestion: String,
    val keep: String,
    val operationalSummary: String,
    val activeVacancies: String,
    val pendingApplications: String,
    val ongoingInternships: String,
    val recentApplications: String,
    val viewAll: String,
    val noPendingApplications: String,
    val newOffer: String,
    val newOfferDescription: String,
    val publishVacancy: String,
    val applicationPrefix: String,
    val evaluate: String,
    val featured: String
)

object AppText {
    const val PT = "pt"
    const val EN = "en"

    fun of(languageCode: String?): AppStrings =
        if (languageCode == EN) englishStrings else portugueseStrings

    private val portugueseStrings = AppStrings(
        languageCode = PT,
        languageName = "Português",
        portuguese = "Português",
        english = "English",
        notifications = "Notificações",
        noNotifications = "Sem notificações",
        clear = "Limpar",
        home = "Início",
        search = "Procurar",
        internship = "Estágio",
        internships = "Estágios",
        students = "Alunos",
        candidates = "Candidatos",
        mentors = "Orientadores",
        chat = "Chat",
        profile = "Perfil",
        userInfoTitle = "Informações\nUtilizador",
        userNameLabel = "NOME DE UTILIZADOR",
        edit = "Editar",
        cancel = "Cancelar",
        save = "Guardar",
        information = "Informações",
        personalInfo = "Informações Pessoais",
        contactInfo = "Informações de Contacto",
        academicData = "Dados Académicos",
        professionalData = "Dados Profissionais",
        institutionalInfo = "Informações Institucionais",
        companyData = "Dados da Empresa",
        settings = "Configurações",
        language = "Idioma",
        logout = "TERMINAR SESSÃO",
        fullName = "NOME COMPLETO",
        corporateEmail = "EMAIL CORPORATIVO",
        institutionalEmail = "E-MAIL INSTITUCIONAL",
        email = "E-MAIL",
        mobile = "TELEMÓVEL",
        phone = "TELEFONE",
        workArea = "ÁREA DE TRABALHO",
        educationInstitution = "INSTITUIÇÃO DE ENSINO",
        course = "CURSO",
        studentNumber = "NÚMERO DE ALUNO",
        address = "MORADA",
        description = "DESCRIÇÃO",
        teacherRole = "DOCENTE",
        companySupervisorRole = "ORIENTADOR DE EMPRESA",
        companyRole = "EMPRESA",
        studentRole = "ALUNO",
        certifiedCompany = "EMPRESA CERTIFICADA",
        pendingApproval = "PENDENTE DE APROVAÇÃO",
        messages = "Mensagens",
        close = "Fechar",
        selectInstitution = "Selecionar instituição",
        searchByNameOrAcronym = "Pesquisar por nome ou sigla",
        noInstitutionsFound = "Sem instituições encontradas",
        hello = "Olá",
        dashboardWelcome = "Bem-vindo ao seu painel de curadoria académica. Aqui está o resumo de hoje.",
        activeMentees = "ORIENTANDOS ATIVOS",
        activitiesThisWeek = "ATIVIDADES ESTA SEMANA",
        missingEvaluations = "AVALIAÇÕES EM FALTA",
        recentActivity = "Atividade Recente",
        noRecentActivity = "Sem atividade recente",
        registeredActivity = "registou uma atividade",
        viewActivities = "Ver atividades",
        myMentees = "Meus Orientandos",
        menteesSubtitle = "Gerencie o progresso académico e profissional dos alunos sob sua supervisão direta.",
        filterByNameOrCourse = "Filtrar por nome ou curso...",
        noMentees = "Sem orientandos",
        hostCompany = "EMPRESA DE ACOLHIMENTO",
        undefinedCompany = "Empresa não definida",
        undefinedCourse = "Curso não definido",
        viewDetailsDiary = "Ver Detalhes/Diário",
        studentJourneySummary = "Aqui está o resumo da tua jornada de estágio hoje.",
        myStatus = "O meu Estado",
        activeApplicationsTracking = "Acompanhamento das tuas candidaturas ativas",
        noApplications = "Sem Candidaturas Efetuadas",
        searchAndApplyInternships = "Procura estágios e submete a tua candidatura!",
        searchInternships = "Procurar Estágios",
        registerActivity = "Registar Atividade",
        hourProgress = "PROGRESSO DE HORAS",
        accumulatedHoursSemester = "Horas acumuladas este semestre",
        cancelApplication = "Cancelar candidatura",
        removeApplication = "Remover candidatura",
        cancelApplicationQuestion = "Queres cancelar a tua candidatura? Poderás voltar a candidatar-te mais tarde.",
        removeApplicationQuestion = "Queres remover o resultado desta candidatura da tua lista?",
        keep = "Manter",
        operationalSummary = "Resumo Operacional",
        activeVacancies = "VAGAS ATIVAS",
        pendingApplications = "CANDIDATURAS PENDENTES",
        ongoingInternships = "ESTÁGIOS A DECORRER",
        recentApplications = "Candidaturas\nRecentes",
        viewAll = "Ver Todas",
        noPendingApplications = "Sem candidaturas pendentes",
        newOffer = "Nova Oferta",
        newOfferDescription = "Crie uma nova oportunidade de estágio para atrair os melhores talentos académicos.",
        publishVacancy = "Publicar Vaga",
        applicationPrefix = "Candidatura",
        evaluate = "Avaliar",
        featured = "DESTAQUE"
    )

    private val englishStrings = AppStrings(
        languageCode = EN,
        languageName = "English",
        portuguese = "Português",
        english = "English",
        notifications = "Notifications",
        noNotifications = "No notifications",
        clear = "Clear",
        home = "Home",
        search = "Search",
        internship = "Internship",
        internships = "Internships",
        students = "Students",
        candidates = "Candidates",
        mentors = "Supervisors",
        chat = "Chat",
        profile = "Profile",
        userInfoTitle = "User\nInformation",
        userNameLabel = "USER NAME",
        edit = "Edit",
        cancel = "Cancel",
        save = "Save",
        information = "Information",
        personalInfo = "Personal Information",
        contactInfo = "Contact Information",
        academicData = "Academic Data",
        professionalData = "Professional Data",
        institutionalInfo = "Institutional Information",
        companyData = "Company Data",
        settings = "Settings",
        language = "Language",
        logout = "LOG OUT",
        fullName = "FULL NAME",
        corporateEmail = "CORPORATE EMAIL",
        institutionalEmail = "INSTITUTIONAL EMAIL",
        email = "EMAIL",
        mobile = "MOBILE",
        phone = "PHONE",
        workArea = "WORK AREA",
        educationInstitution = "EDUCATION INSTITUTION",
        course = "COURSE",
        studentNumber = "STUDENT NUMBER",
        address = "ADDRESS",
        description = "DESCRIPTION",
        teacherRole = "TEACHER",
        companySupervisorRole = "COMPANY SUPERVISOR",
        companyRole = "COMPANY",
        studentRole = "STUDENT",
        certifiedCompany = "CERTIFIED COMPANY",
        pendingApproval = "PENDING APPROVAL",
        messages = "Messages",
        close = "Close",
        selectInstitution = "Select institution",
        searchByNameOrAcronym = "Search by name or acronym",
        noInstitutionsFound = "No institutions found",
        hello = "Hello",
        dashboardWelcome = "Welcome to your academic supervision panel. Here is today's summary.",
        activeMentees = "ACTIVE STUDENTS",
        activitiesThisWeek = "ACTIVITIES THIS WEEK",
        missingEvaluations = "MISSING EVALUATIONS",
        recentActivity = "Recent Activity",
        noRecentActivity = "No recent activity",
        registeredActivity = "registered an activity",
        viewActivities = "View activities",
        myMentees = "My Students",
        menteesSubtitle = "Manage the academic and professional progress of the students under your direct supervision.",
        filterByNameOrCourse = "Filter by name or course...",
        noMentees = "No students",
        hostCompany = "HOST COMPANY",
        undefinedCompany = "Company not defined",
        undefinedCourse = "Course not defined",
        viewDetailsDiary = "View Details/Diary",
        studentJourneySummary = "Here is the summary of your internship journey today.",
        myStatus = "My Status",
        activeApplicationsTracking = "Tracking your active applications",
        noApplications = "No Applications Submitted",
        searchAndApplyInternships = "Search internships and submit your application!",
        searchInternships = "Search Internships",
        registerActivity = "Register Activity",
        hourProgress = "HOUR PROGRESS",
        accumulatedHoursSemester = "Hours accumulated this semester",
        cancelApplication = "Cancel application",
        removeApplication = "Remove application",
        cancelApplicationQuestion = "Do you want to cancel your application? You can apply again later.",
        removeApplicationQuestion = "Do you want to remove this application result from your list?",
        keep = "Keep",
        operationalSummary = "Operational Summary",
        activeVacancies = "ACTIVE VACANCIES",
        pendingApplications = "PENDING APPLICATIONS",
        ongoingInternships = "ONGOING INTERNSHIPS",
        recentApplications = "Recent\nApplications",
        viewAll = "View All",
        noPendingApplications = "No pending applications",
        newOffer = "New Offer",
        newOfferDescription = "Create a new internship opportunity to attract the best academic talent.",
        publishVacancy = "Publish Vacancy",
        applicationPrefix = "Application",
        evaluate = "Evaluate",
        featured = "FEATURED"
    )
}
